# EXPLORATORY DATA ANALYSIS (EDA):

## Project Context:

This notebook contains the Exploratory Data Analysis (EDA) for the Marketing Campaign Analysis and Optimization project.
The dataset captures performance metrics across multiple marketing campaigns, including spend, impressions, clicks, conversions, and revenue related measures, along with key categorical dimensions such as channel, region, and campaign identifiers.

This EDA is conducted after feature engineering and focuses on validating data quality, understanding metric behavior, and identifying performance patterns and risks.

#### Objective:

The very objective of this EDA notebook is to:
- Validate the integrity and reliability of the engineered features
- Understand the distribution and behavior of key performance metrics
- Examine relationships and tradeoffs between cost, volume, and efficiency
- Identify segment-level performance differences and risks
- Surface insights that can inform further analysis or modeling
- This analysis is descriptive and diagnostic, not prescriptive.

#### Business Questions Addressed:

This notebook aims to answer the following high-level questions:
- Can the campaign performance data be trusted for analysis?
- How do core marketing metrics behave in isolation and in relation to one another?
- What cost-efficiency tradeoffs are observable in the data?
- How does performance vary across channels, regions, and campaign segments?
- Where are the major data risks, outliers, or instability points?

### My Goal: Explore data patterns & insights:

#### Tasks:
- Distribution plots (budget, impressions, clicks, conversions)
- Correlations between metrics (budget vs conversions, CTR vs CR)
- Channel-level comparisons (Email vs SEO vs Social vs Display Ads)
- Identify trends (monthly conversions, CTR over time)
- Document key anomalies (e.g., campaigns with high spend but low CR)
- Im still thinking what other things to address at this point

#### Dataset Description:

- Data domain: Marketing campaign performance data cleaned and featured 
- Granularity: Campaign-level
- Time range: (still to be confirmed in Phase 1)
- Core metric types:
    - Volume metrics (impressions, clicks, spend, revenue)
    - Efficiency metrics (CTR, CPC, CPA, ROAS, ROI)
- Key dimensions:
    - Channel
    - Region
    - Campaign / campaign type
    - Time (date)

### Import Libraries:

In [123]:
# Libraries

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

pd.options.display.float_format = '{:,.4f}'.format

### Ingest Data as DF:

In [124]:
# INGEST DATA

df = pd.read_csv("../data/processed/marketing_campaign_2024_2025_processed.csv")

## PHASE 1: Dataset Overview & Structural Integrity

### Dataset Shape + Columnnames andd dtypes:

In [125]:
# Dataset Shape + Columnnames andd dtypes

print(df.shape)
df.info()

# Assess distributional shape of core metrics:
    # Row count is reasonable for campaign level analysis
    # Column count aligns with expected metrics and dimensions
    # Metric columns are numeric
    # Categorical dimensions are object or category
    # Date column is not datetime -- needs to be addressed

(1831, 42)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1831 entries, 0 to 1830
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   campaign_id                1831 non-null   object
 1   campaign_name              1831 non-null   object
 2   start_date                 1831 non-null   object
 3   end_date                   1831 non-null   object
 4   channel                    1831 non-null   object
 5   region                     1831 non-null   object
 6   impressions                1831 non-null   int64
 7   clicks                     1831 non-null   int64
 8   conversions                1831 non-null   int64
 9   spend_usd                  1831 non-null   float64
 10  revenue_usd                1831 non-null   float64
 11  target_audience            1831 non-null   object
 12  product_category           1831 non-null   object
 13  device                     1831 non-null   object
 14  year                       1831 non-null   int64
 15  data_source                1831 non-null   object
 16  campaign_duration_days     1831 non-null   int64
 17  month                      1831 non-null   int64
 18  quarter                    1831 non-null   int64
 19  start_month                1831 non-null   int64
 20  end_month                  1831 non-null   int64
 21  is_holiday_season          1831 non-null   bool
 22  ctr                        1831 non-null   float64
 23  conversion_rate            1831 non-null   float64
 24  roi                        1831 non-null   float64
 25  roas                       1831 non-null   float64
 26  cpc                        1831 non-null   float64
 27  cpm                        1831 non-null   float64
 28  cpa                        1831 non-null   float64
 29  revenue_per_click          1831 non-null   float64
 30  revenue_per_conversion     1831 non-null   float64
 31  profit                     1831 non-null   float64
 32  profit_margin              1831 non-null   float64
 33  impressions_to_conversion  1831 non-null   float64
 34  click_to_conv_ratio        1831 non-null   float64
 35  midpoint_month             1831 non-null   int64
 36  season_label               1831 non-null   object
 37  engagement_rate_1000       1831 non-null   float64
 38  rev_per_1000               1831 non-null   float64
 39  roi_flag                   1831 non-null   int64
 40  midpoint_date              1831 non-null   object
 41  funnel_issue_flag          1831 non-null   bool
dtypes: bool(2), float64(17), int64(11), object(12)
memory usage: 575.9+ KB

### Sample rows check:

In [126]:
# sample rows lead
df.head()

,campaign_id,campaign_name,start_date,end_date,channel,region,impressions,clicks,conversions,spend_usd,...,profit_margin,impressions_to_conversion,click_to_conv_ratio,midpoint_month,season_label,engagement_rate_1000,rev_per_1000,roi_flag,midpoint_date,funnel_issue_flag
0,2024_0001,Campaign_2024_0001,2024-05-16,2024-08-16,Google Ads,South America,28252,5609,5609,"39,193.4300",...,0.5040,0.1985,1.0000,7,Summer,397.0692,"2,796.8901",0,2024-07-01 00:00:00,False
1,2024_0002,Campaign_2024_0002,2024-04-06,2024-10-13,Google Ads,Asia,89608,83584,26865,"17,291.5300",...,0.6533,0.2998,0.3214,7,Summer,"1,232.5797",556.5188,1,2024-07-10 00:00:00,False
2,2024_0003,Campaign_2024_0003,2024-05-08,2024-11-27,Facebook Ads,Europe,37853,37853,37853,"6,729.6300",...,0.8932,1.0000,1.0000,8,Summer,"2,000.0000","1,664.8953",1,2024-08-17 12:00:00,False
3,2024_0004,Campaign_2024_0004,2024-01-28,2024-08-03,Google Display Network,Africa,10577,10577,10577,"15,077.5800",...,0.8867,1.0000,1.0000,5,New Year,"2,000.0000","12,584.5429",1,2024-05-01 00:00:00,False
4,2024_0005,Campaign_2024_0005,2024-02-06,2024-08-23,Facebook Ads,Asia,84039,56010,11283,"16,877.6900",...,0.8834,0.1343,0.2014,5,New Year,800.7354,"1,722.2598",1,2024-05-15 12:00:00,False

In [127]:
# sample rows tails
df.tail()

,campaign_id,campaign_name,start_date,end_date,channel,region,impressions,clicks,conversions,spend_usd,...,profit_margin,impressions_to_conversion,click_to_conv_ratio,midpoint_month,season_label,engagement_rate_1000,rev_per_1000,roi_flag,midpoint_date,funnel_issue_flag
1826,2024_JD_0778,Campaign_2024_JD_0778,2024-12-30,2025-01-06,TikTok Ads,Africa,137632,14988,1415,"11,741.4900",...,0.7097,0.0103,0.0944,1,Holiday Peak,119.1801,293.8521,1,2025-01-02 12:00:00,False
1827,2024_JD_0777,Campaign_2024_JD_0777,2024-12-30,2025-01-06,Google Ads,Africa,134951,15552,842,"8,453.1100",...,0.5481,0.0062,0.0541,1,Holiday Peak,121.4811,138.6027,0,2025-01-02 12:00:00,False
1828,2024_JD_0775,Campaign_2024_JD_0775,2024-12-30,2025-01-06,TikTok Ads,South America,133585,17131,1145,"41,260.7500",...,0.5578,0.0086,0.0668,1,Holiday Peak,136.8118,698.5163,0,2025-01-02 12:00:00,False
1829,2024_JD_0776,Campaign_2024_JD_0776,2024-12-30,2025-01-06,TikTok Ads,South America,133585,17131,1145,"41,260.7500",...,0.5578,0.0086,0.0668,1,Holiday Peak,136.8118,698.5163,0,2025-01-02 12:00:00,False
1830,2024_JD_0774,Campaign_2024_JD_0774,2024-12-30,2025-01-06,Google Ads,South America,132734,18486,4210,"23,056.1000",...,0.4193,0.0317,0.2277,1,Holiday Peak,170.9886,299.1173,0,2025-01-02 12:00:00,False

In [128]:
# so far the values align with column meaning
# No obvious placeholder values
# Metrics appear within reasonable ranges
# No unexpected null patterns at the beginning or end

### Date Coverage:

In [129]:
# Date Coverage

# df["start_date"].min(), df["start_date"].max()  # check startdate
# df["end_date"].min(), df["end_date"].max()  # check end_date
# df["month"].min(), df["month"].max()  # check month
# df["start_month"].min(), df["start_month"].max()  # check start_month
# df["end_month"].min(), df["end_month"].max()  # check end_month
# df["year"].min(), df["year"].max()  # check year

summary = {
    col: {"min": df[col].min(), "max": df[col].max()}
    for col in [
        "start_date", "end_date", "month",
        "start_month", "end_month", "campaign_duration_days", "year"
    ]
}

pd.DataFrame(summary).T

# Start and end dates make sense for the project
# Coverage aligns with expectations from the data source
# No future or implausible dates
# i want to ceck if aggregations will not misleading

                               min         max
start_date              2024-01-01  2025-06-30
end_date                2024-07-02  2025-12-31
month                            1          12
start_month                      1          12
end_month                        1          12
campaign_duration_days           4         364
year                          2024        2025

##### Convert date columns to datetime:

In [130]:
# Convert date columns to datetime

date_cols = ["start_date", "end_date", "midpoint_date"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')  # coerce invalid parses to NaT

# Confirm conversion
df[date_cols].info()
df[date_cols].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1831 entries, 0 to 1830
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   start_date     1831 non-null   datetime64[ns]
 1   end_date       1831 non-null   datetime64[ns]
 2   midpoint_date  1831 non-null   datetime64[ns]
dtypes: datetime64[ns](3)
memory usage: 43.0 KB

  start_date   end_date       midpoint_date
0 2024-05-16 2024-08-16 2024-07-01 00:00:00
1 2024-04-06 2024-10-13 2024-07-10 00:00:00
2 2024-05-08 2024-11-27 2024-08-17 12:00:00
3 2024-01-28 2024-08-03 2024-05-01 00:00:00
4 2024-02-06 2024-08-23 2024-05-15 12:00:00

##### Date Parsing:

In [131]:
# Date Parsing Validation:

# check min & max dates per date column

date_cols_check = {
    col: {"min": df[col].min(), "max": df[col].max()}
    for col in ["start_date", "end_date", "midpoint_date"]
}

pd.DataFrame(date_cols_check).T

                              min        max
start_date    2024-01-01 00:00:00 2025-06-30
end_date      2024-07-02 00:00:00 2025-12-31
midpoint_date 2024-04-05 12:00:00 2025-09-28

##### Date Parsing Validation:

In [132]:
# Date Parsing Validation:

# cath the imposible dates + basic duration sanity check

invalid_campaigns = df[df["end_date"] < df["start_date"]]

print("Invalid campaigns (end before start):", invalid_campaigns.shape[0])

# This ensures all campaigns have start_date ≤ end_date
# 0 results means its good to go

Invalid campaigns (end before start): 0

##### midpoint_date_computed:

In [133]:
# midpoint_date_computed:

# Compute midpoint from start_date and end_date
df['midpoint_date_computed'] = df['start_date'] + (df['end_date'] - df['start_date']) / 2

# Compare with existing midpoint_date
inconsistent_midpoints = df[df['midpoint_date'] != df['midpoint_date_computed']]

print("Number of campaigns with inconsistent midpoint_date:", inconsistent_midpoints.shape[0])

# Optional: inspect first few inconsistencies
inconsistent_midpoints[['campaign_id', 'start_date', 'end_date', 'midpoint_date', 'midpoint_date_computed']]

Number of campaigns with inconsistent midpoint_date: 0

Empty DataFrame
Columns: [campaign_id, start_date, end_date, midpoint_date, midpoint_date_computed]
Index: []

##### midpoint_date_computed validation:

In [134]:
# midpoint_date_computed validation:

df['midpoint_date'] = df['midpoint_date_computed']
df.drop(columns=['midpoint_date_computed'], inplace=True)

# No result on created temporary table means midpoint_date is fully consistent with the start and end dates
# start_date, end_date, and midpoint_date properly parsed as datetime
# No inconsistencies or errors in midpoint calculation

### Duplicate Checks:

In [135]:
# Duplicate Checks:

df.duplicated().sum()

# Duplicate rows checked explicitly, no duplicated records detected.
# Duplicate count is zero (Nulls ≠ duplicates)
# No unintended row duplication that would inflate metrics
# looks good to me

np.int64(0)

### Numeric Integrity + Metric sanity checking:

In [136]:
# Numeric Integrity + Metric sanity checking:

numeric_cols = df.select_dtypes(include='number').columns

df[numeric_cols].describe().T

# Do numeric features look structurally and mathematically sane?
# Does this data make sense to analyze?

# this dataset is structurally analyzable, but it clearly contains:
    # Heavy skew
    # Extreme outliers
    # Ratio inflation artifacts
    # Binary felds leaking into numeric summaries (roi_flag is binary but appears in numeric summaries - should be bolean tho)

,count,mean,std,min,25%,50%,75%,max
impressions,"1,831.0000","74,943.7788","50,331.1146","1,034.0000","35,807.5000","67,696.0000","98,318.0000","199,027.0000"
clicks,"1,831.0000","21,113.1491","20,284.3329",86.0000,"5,755.5000","13,487.0000","30,780.0000","89,352.0000"
conversions,"1,831.0000","12,952.8471","16,535.2505",4.0000,962.0000,"4,424.0000","20,834.0000","79,692.0000"
spend_usd,"1,831.0000","25,733.9855","13,839.3821","1,066.1100","14,339.4600","25,931.8900","37,271.8250","49,908.4500"
revenue_usd,"1,831.0000","69,212.1397","41,545.3485","1,098.6600","35,753.5600","65,667.7700","102,387.8550","172,113.1500"
year,"1,831.0000","2,024.2731",0.4457,"2,024.0000","2,024.0000","2,024.0000","2,025.0000","2,025.0000"
campaign_duration_days,"1,831.0000",125.0535,85.4753,4.0000,51.5000,117.0000,187.0000,364.0000
month,"1,831.0000",6.3736,3.5501,1.0000,3.0000,6.0000,10.0000,12.0000
quarter,"1,831.0000",2.4473,1.1387,1.0000,1.0000,2.0000,4.0000,4.0000
start_month,"1,831.0000",6.3736,3.5501,1.0000,3.0000,6.0000,10.0000,12.0000
end_month,"1,831.0000",10.1447,2.1654,1.0000,9.0000,11.0000,12.0000,12.0000
ctr,"1,831.0000",0.4318,0.4016,0.0015,0.0834,0.1500,0.9600,1.0000
conversion_rate,"1,831.0000",0.5180,0.4020,0.0005,0.1511,0.2946,1.0000,1.0000
roi,"1,831.0000",3.3049,8.0164,-0.9736,0.6634,1.5918,2.4178,132.4438
roas,"1,831.0000",4.3049,8.0164,0.0264,1.6634,2.5918,3.4178,133.4438
cpc,"1,831.0000",5.6057,20.5978,0.0253,0.6441,1.6132,4.2728,561.8712
cpm,"1,831.0000",817.8558,"1,936.6498",7.2564,180.3652,369.9433,744.8936,"31,726.2959"
cpa,"1,831.0000",46.9226,261.0013,0.0316,1.0507,4.1925,23.5973,"8,781.2650"
revenue_per_click,"1,831.0000",13.9847,43.8671,0.0133,1.7924,4.2187,10.1933,"1,038.0850"
revenue_per_conversion,"1,831.0000",120.2503,740.4753,0.0344,3.0650,11.4798,58.2574,"24,718.7000"
profit,"1,831.0000","43,478.1543","39,149.4354","-45,604.0400","13,206.9300","37,218.6700","71,677.8300","148,270.8000"
profit_margin,"1,831.0000",0.2964,1.7108,-36.8881,0.3988,0.6142,0.7074,0.9925
impressions_to_conversion,"1,831.0000",0.3209,0.3875,0.0002,0.0115,0.0814,0.6324,1.0000
click_to_conv_ratio,"1,831.0000",0.5180,0.4020,0.0005,0.1511,0.2946,1.0000,1.0000
midpoint_month,"1,831.0000",8.3812,2.4948,1.0000,6.0000,8.0000,11.0000,12.0000
engagement_rate_1000,"1,831.0000",752.6996,764.9462,2.9389,101.6502,284.6225,"1,454.6961","2,000.0000"
rev_per_1000,"1,831.0000","2,421.7802","6,115.1607",11.5347,439.9562,943.8065,"2,045.8426","84,749.4754"
roi_flag,"1,831.0000",0.4997,0.5001,0.0000,0.0000,0.0000,1.0000,1.0000

### Categorical Structure + Cardinality Check:

##### Categorical:

In [137]:
# Category = df[["impressions", "clicks", "conversions"]].describe().T

cat_summary = df.select_dtypes(include=["object", "category"]).describe().T

cat_summary

# so far clear identifiers
# Reasonable category counts
# No obvious cardinality traps (except IDs, thats expected)

                 count unique                 top freq
campaign_id       1831   1831           2024_0001    1
campaign_name     1831   1831  Campaign_2024_0001    1
channel           1831      5               Email  389
region            1831      5              Africa  380
target_audience   1831      3              Adults  620
product_category  1831      7                Home  376
device            1831      3              Mobile  647
data_source       1831      3             H2_2024  831
season_label      1831      4              Summer  514

In [138]:
# campaign_id, campaign_name - perfect one-to-one identifiers & no dups They have high cardinality
# start_date, end_date, midpoint_date - High cardinality (hundreds of unique values) & end_date = 2024-12-31 appears 304 times
    # start dates more spread
    # campaigns ended at year-end (batch termination)
    # Date columns parsed to datetime; categorical summary used only to inspect cardinality patterns.
    # should be datetime, not categorical (i believe i had issues converting this last time)
# channel, region, target_audience, product_category, device - so far has no exploding categories 
    # these core dimensions have manageable cardinality and are suitable for grouping analysis.
# data_source, season_label - are metadata they have low cardinality
    # Identifier columns or metadata should be excluded from aggregation

##### Volume & Exposure Metrics:

In [139]:
# Volume & Exposure Metrics

Category = df[["impressions", "clicks", "conversions"]].describe().T

Category

# Distributional skew expected due to campaign scale differences
# if you look closely its wihin the reasonable magnitudes
# & logical ordering holds (impressions > clicks > conversions)
# ong right tails (expected) + No zero or negative values

,count,mean,std,min,25%,50%,75%,max
impressions,"1,831.0000","74,943.7788","50,331.1146","1,034.0000","35,807.5000","67,696.0000","98,318.0000","199,027.0000"
clicks,"1,831.0000","21,113.1491","20,284.3329",86.0000,"5,755.5000","13,487.0000","30,780.0000","89,352.0000"
conversions,"1,831.0000","12,952.8471","16,535.2505",4.0000,962.0000,"4,424.0000","20,834.0000","79,692.0000"

##### Financial Metrics:

In [140]:
# Financial Metrics

FinCategory = df[["spend_usd", "revenue_usd", "profit"]].describe().T

FinCategory

# Profit distribution is asymmetric, it means inflated by high-performing campaigns
# Revenue consistently ≥ spend on median
# No zero spend rows (important for ratio stability)
# Profit has heavy right skew

,count,mean,std,min,25%,50%,75%,max
spend_usd,"1,831.0000","25,733.9855","13,839.3821","1,066.1100","14,339.4600","25,931.8900","37,271.8250","49,908.4500"
revenue_usd,"1,831.0000","69,212.1397","41,545.3485","1,098.6600","35,753.5600","65,667.7700","102,387.8550","172,113.1500"
profit,"1,831.0000","43,478.1543","39,149.4354","-45,604.0400","13,206.9300","37,218.6700","71,677.8300","148,270.8000"

##### Time & Duration:

In [141]:
# Time & Duration

DCategory = df[["year", "month", "quarter", "start_month", "end_month", "midpoint_month", "campaign_duration_days"]].describe().T

DCategory

# Coverage year of only 2024–2025
# Month columns are categorical encoded as numeric -- done with this
# Month-based fields treated as categorical/time dimensions, not numeric measures -- done with this

,count,mean,std,min,25%,50%,75%,max
year,"1,831.0000","2,024.2731",0.4457,"2,024.0000","2,024.0000","2,024.0000","2,025.0000","2,025.0000"
month,"1,831.0000",6.3736,3.5501,1.0000,3.0000,6.0000,10.0000,12.0000
quarter,"1,831.0000",2.4473,1.1387,1.0000,1.0000,2.0000,4.0000,4.0000
start_month,"1,831.0000",6.3736,3.5501,1.0000,3.0000,6.0000,10.0000,12.0000
end_month,"1,831.0000",10.1447,2.1654,1.0000,9.0000,11.0000,12.0000,12.0000
midpoint_month,"1,831.0000",8.3812,2.4948,1.0000,6.0000,8.0000,11.0000,12.0000
campaign_duration_days,"1,831.0000",125.0535,85.4753,4.0000,51.5000,117.0000,187.0000,364.0000

##### Rate & Ratios:

In [142]:
# Rate & Ratios:

RRCategory = df[["ctr", "conversion_rate", "click_to_conv_ratio", "impressions_to_conversion"]].describe().T

RRCategory

# All within logical bounds of 0 and 1 [0, 1]
# No values >1
# Median more informative than mean
# Rate metrics analyzed using median/quantiles rather than mean.

,count,mean,std,min,25%,50%,75%,max
ctr,"1,831.0000",0.4318,0.4016,0.0015,0.0834,0.1500,0.9600,1.0000
conversion_rate,"1,831.0000",0.5180,0.4020,0.0005,0.1511,0.2946,1.0000,1.0000
click_to_conv_ratio,"1,831.0000",0.5180,0.4020,0.0005,0.1511,0.2946,1.0000,1.0000
impressions_to_conversion,"1,831.0000",0.3209,0.3875,0.0002,0.0115,0.0814,0.6324,1.0000

##### ROI / Efficiency Metrics:

In [143]:
# ROI / Efficiency Metrics:

RECategory = df[["roi", "roas", "cpc", "cpm", "cpa"]].describe().T

RECategory

# Negative ROI exists, thats ok
# ROAS mirrors ROI + 1
# Extreme outliers:
    # ROI max = 132
    # CPC max = 561
    # CPA max = 8,781
# outliers will be handled via robust statistics and/or log scale
# most likely a very small denominators (low spend, few clicks/conversions) this greatly affects the mean

,count,mean,std,min,25%,50%,75%,max
roi,"1,831.0000",3.3049,8.0164,-0.9736,0.6634,1.5918,2.4178,132.4438
roas,"1,831.0000",4.3049,8.0164,0.0264,1.6634,2.5918,3.4178,133.4438
cpc,"1,831.0000",5.6057,20.5978,0.0253,0.6441,1.6132,4.2728,561.8712
cpm,"1,831.0000",817.8558,"1,936.6498",7.2564,180.3652,369.9433,744.8936,"31,726.2959"
cpa,"1,831.0000",46.9226,261.0013,0.0316,1.0507,4.1925,23.5973,"8,781.2650"

##### Revenue Density Metrics:

In [144]:
# ROI / Efficiency Metrics:

RevCategory = df[["revenue_per_click", "revenue_per_conversion", "rev_per_1000"]].describe().T

RevCategory

# No impossible negatives
# theres hhis severe long tails (order-of-magnitude jumps)
# A small number of high-value conversions dominate averages
# Revenue-per-unit metrics exhibit extreme skew
# analysis focuses on distributional shape, not central tendency.

,count,mean,std,min,25%,50%,75%,max
revenue_per_click,"1,831.0000",13.9847,43.8671,0.0133,1.7924,4.2187,10.1933,"1,038.0850"
revenue_per_conversion,"1,831.0000",120.2503,740.4753,0.0344,3.0650,11.4798,58.2574,"24,718.7000"
rev_per_1000,"1,831.0000","2,421.7802","6,115.1607",11.5347,439.9562,943.8065,"2,045.8426","84,749.4754"

##### Margin:

In [145]:
# Margin:

MCategory = df["profit_margin"].describe()

MCategory

# Negative margins exist (it occurs when revenue ≪ spend)
# theres an extremely negative values at (-36) (Mathematically valid but analytically dangerous)
# Profit margin clipped or log-transformed for visualization only

count   1,831.0000
mean        0.2964
std         1.7108
min       -36.8881
25%         0.3988
50%         0.6142
75%         0.7074
max         0.9925
Name: profit_margin, dtype: float64

##### Binary Leakage:

In [146]:
# Binary Leakage:

LCategory = df["roi_flag"].describe()

LCategory

# Appears in numeric summaries
# Values are clean with 0 & 1 
# Convert to boolean
# Binary flags mmust be excluded from numeric distribution analysis.

count   1,831.0000
mean        0.4997
std         0.5001
min         0.0000
25%         0.0000
50%         0.0000
75%         1.0000
max         1.0000
Name: roi_flag, dtype: float64

### PHASE 1: Summary

This phase validated the structural, mathematical, and semantic integrity of the dataset.
Both numeric and categorical features were inspected to confirm correctness, consistency, and analytical readiness.

Expected characteristics of marketing data were observed, including heavy skew, long-tailed distributions, and the presence of outliers, particularly in cost, efficiency, and revenue-based metrics. These behaviors are documented and intentionally not corrected at this stage.

No outlier removal, normalization for modeling, optimization, ranking, or causal assumptions were performed in this phase.

Conclusion: The dataset is structurally sound and analytically trustworthy, with no integrity issues blocking further exploratory analysis.
also note: Distributional behavior is noted here for integrity validation; detailed distribution analysis begins in Phase 2.

In [147]:
print(df.shape)
df.info()

(1831, 42)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1831 entries, 0 to 1830
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   campaign_id                1831 non-null   object
 1   campaign_name              1831 non-null   object
 2   start_date                 1831 non-null   datetime64[ns]
 3   end_date                   1831 non-null   datetime64[ns]
 4   channel                    1831 non-null   object
 5   region                     1831 non-null   object
 6   impressions                1831 non-null   int64
 7   clicks                     1831 non-null   int64
 8   conversions                1831 non-null   int64
 9   spend_usd                  1831 non-null   float64
 10  revenue_usd                1831 non-null   float64
 11  target_audience            1831 non-null   object
 12  product_category           1831 non-null   object
 13  device                     1831 non-null   object
 14  year                       1831 non-null   int64
 15  data_source                1831 non-null   object
 16  campaign_duration_days     1831 non-null   int64
 17  month                      1831 non-null   int64
 18  quarter                    1831 non-null   int64
 19  start_month                1831 non-null   int64
 20  end_month                  1831 non-null   int64
 21  is_holiday_season          1831 non-null   bool
 22  ctr                        1831 non-null   float64
 23  conversion_rate            1831 non-null   float64
 24  roi                        1831 non-null   float64
 25  roas                       1831 non-null   float64
 26  cpc                        1831 non-null   float64
 27  cpm                        1831 non-null   float64
 28  cpa                        1831 non-null   float64
 29  revenue_per_click          1831 non-null   float64
 30  revenue_per_conversion     1831 non-null   float64
 31  profit                     1831 non-null   float64
 32  profit_margin              1831 non-null   float64
 33  impressions_to_conversion  1831 non-null   float64
 34  click_to_conv_ratio        1831 non-null   float64
 35  midpoint_month             1831 non-null   int64
 36  season_label               1831 non-null   object
 37  engagement_rate_1000       1831 non-null   float64
 38  rev_per_1000               1831 non-null   float64
 39  roi_flag                   1831 non-null   int64
 40  midpoint_date              1831 non-null   datetime64[ns]
 41  funnel_issue_flag          1831 non-null   bool
dtypes: bool(2), datetime64[ns](3), float64(17), int64(11), object(9)
memory usage: 575.9+ KB